### ISSUE TITLE
7

### ISSUE THREAD

**Issue by AnAsteria** [AnAsteria/my-first-repo#5]
刚发现我7也不会做捂脸，麻烦姐妹发一下

**Comment by mycorfu** [comment]
z3N4FKe6ntuChFx4dgWaNrKsXtSe/e78MPth94p97vb91i/rPMOB96Q/grZ6SD9V2Xt9n5q7vD7B/ZGCtxU9IkzoPz+nuiwplkBN6A424/mY0q6CWae7wdMIED8hhZsdbjoiplNw00SXXMauQIm+So0taDMBEcyeN5MiKWd8Rv6sgIjv6z1xGwPyfKb6P4QQ8qhpzEc6/rzUFcR/3O9ft7aq/EhjRCQSPHtXtOtHMgHpOvRxCY++vbBeM52ow8kFYFiQcgf3TVIziaEvUkLCSbA7KWtYS0kmdIFZqWRzRq3+cqAeL9wcYCC8E8BwcrZnUrkrLq163dopY2Bbm8KMBFiLjbS3iajSAKaRcG8v2OKC72+9f97YqYZA212TiO5yNI2wiFwweNJVPhqjcT1gj5UPV81v31hPyTkw5DQkOCdL1LiYd6ASE45tVRtPxGPphqr0kX+90bw=

**Comment by mycorfu** [comment]
(* 9. Write in Coq a function that rotates a list. Namely, the call to
(rotate l) returns a new list that is the same as l except that the last 
element of l instead appears as the first element of the new list. *)

Fixpoint rev (l: list nat) : list nat :=
  match l with
  | nil    => nil
  | h :: t => rev t ++ [h]
  end.

Definition getfirst(l : list nat ) : list nat :=
  match l with
  |nil => nil
  |h::t=> [h]
end.

Definition remove_first (l : list nat ) : list nat :=
  match l with
  |nil => nil
  |h::t => t
end.


Definition rotate (l : list nat) : list nat :=
getfirst(rev l) ++ rev (remove_first(rev l)).

Compute rotate [1;2;3;4;5].

Example rotate_test : rotate [1;2;3;4;5] = [5;1;2;3;4].
Proof. simpl. reflexivity. Qed.
